filter:
    excluded_paths: [tests/*, bootstrap/*, config/*, database/*, public/*, resources/*, routes/*, storage/*, vendor/*]
checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php:
            version: 7.2
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --configuration phpunit.coverage.xml --coverage-text'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'

tools:
    external_code_coverage: false
    php_mess_detector: true
    php_cpd: false
    php_pdepend:
        excluded_dirs: [tests, bootstrap, config, database, public, resources, routes, storage, vendor]
