language: php

php:
  - 8.0
  - 8.1

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  - php -r "file_exists('.env') || copy('.env.example', '.env');"
  - php artisan key:generate --force --quiet
  - chmod -R 777 storage bootstrap/cache
  - touch storage/database/testing.sqlite

script: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-text
